entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true  # Only for development

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: pkrhtdm@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web