name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Install Docker if not present
          if ! command -v docker &> /dev/null
          then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
          fi

          # Install Docker Compose if not present
          if ! command -v docker-compose &> /dev/null
          then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Navigate into the repository directory
          cd ~/website

          # Add repository to Git's safe directories (address dubious ownership)
          git config --global --add safe.directory /home/${{ secrets.EC2_USER }}/website

          # Add user to docker group and apply group membership (address permission denied)
          sudo usermod -aG docker $USER
          newgrp docker || true # Use || true to prevent workflow failure if newgrp fails

          # Run Git pull and Docker Compose
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF